# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GlbDNS
version:      0.29
version_from: lib/GlbDNS.pm
installdirs:  site
requires:
    Geo::IP:                       0
    Working::Daemon:               0.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
